
export const ModalDialog = {
  SETTINGS: 'SETTINGS',
  ALERT_DIALOG: 'ALERT_DIALOG',
  EXCEPTION: 'EXCEPTION',
  MSG: 'MSG',

  EDIT_WATCH_GROUP: 'EWG',
  EDIT_WATCH_LIST: 'EWL',
  ADD_TO_WATCH: 'AW'
};
